In [ ]:
import numpy as np
import hashlib

Name A: Marcus Stephan Nordal

Name B: Silviu Mihai

In [ ]:
#Four (4) 'relevant' TDT4305 sentences

Sentence_1 = "The Big Data platform for students is Blackboard"
#sentence_1 = ['big', 'blackboard', 'data', 'platform', 'students']
Sentence_2 = "Questions on MinHash project by NTNU students is on Piazza"
#sentence_2 = ['minhash', 'ntnu', 'piazza', 'project', 'questions', 'students']
Sentence_3 = "NTNU Big Data platform are Blackboard and Piazza"
#sentence_3 = ['big', 'blackboard', 'data', 'ntnu', 'piazza', 'platform']
Sentence_4 = "The project data for students are on Blackboard not Piazza"
#sentence_4 = ['blackboard', 'data', 'piazza', 'project', 'students']

In [ ]:
unique_words = ['big', 'blackboard', 'data', 'minhash', 'ntnu', 'piazza', 'platform', 'project', 'questions', 'students'] # Enter the unique words list here



In [ ]:
# User input

print(f"Format: ['word', 'word', 'word' ...] & watch out for white spaces before comma")
user_input = str(input("Enter your created list of unique words: ")) 

f = open("encrypted_dictionary.txt", "r")
encrypted_words = f.read()


# Hash the user input
hashed_user_input = hashlib.sha256(user_input.encode()).hexdigest()

# Compare with the stored hash
if hashed_user_input == encrypted_words:
    print("Correct! Your dictionary matched!")
else:
    print("Incorrect! Try again.")

In [616]:
Input_Matrix = [] 

In [617]:
## Compute the values for the input matrix here ##

Sentence_1 = Sentence_1.lower()
Sentence_2 = Sentence_2.lower()
Sentence_3 = Sentence_3.lower()
Sentence_4 = Sentence_4.lower()

sentences = [Sentence_1, Sentence_2, Sentence_3, Sentence_4]

input_matrix = [
    [1 if word in Sentence_1 else 0 for word in unique_words],
    [1 if word in Sentence_2 else 0 for word in unique_words],
    [1 if word in Sentence_3 else 0 for word in unique_words],
    [1 if word in Sentence_4 else 0 for word in unique_words]
]
print("Input Matrix:")
print(input_matrix)
print("\n")

# transposed the matrix to make it easier to use in the minhash algorithm (rows become columns)
input_matrix = np.transpose(input_matrix)
print("Input Matrix transposed:")
print(input_matrix)



Input Matrix:
[[1, 1, 1, 0, 0, 0, 1, 0, 0, 1], [0, 0, 0, 1, 1, 1, 0, 1, 1, 1], [1, 1, 1, 0, 1, 1, 1, 0, 0, 0], [0, 1, 1, 0, 0, 1, 0, 1, 0, 1]]


Input Matrix transposed:
[[1 0 1 0]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]]


In [618]:
Sig_M = np.array(np.ones((3,4)) * np.inf) # Create a MinHash signature matrix array with inf values

print(Sig_M)





[[inf inf inf inf]
 [inf inf inf inf]
 [inf inf inf inf]]


In [619]:
Input_Matrix = input_matrix
print("Input Matrix:")
print(Input_Matrix)

Input Matrix:
[[1 0 1 0]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [1 1 0 1]]


In [620]:
# Generate hash functions
#h1 = (x + 3) mod 10 + 1
#h2 = (7x + 1) mod 10 + 1
#h3 = (7x + 2) mod 10 + 1


In [621]:
hash_1 = lambda x,a=1, b=3: (a*x + b) % 10 + 1


In [622]:
hash_2 = lambda x,a=7, b=1: (a*x + b) % 10 + 1


In [623]:
hash_3 = lambda x,a=7, b=2: (a*x + b) % 10 + 1

In [624]:
hash_list = [hash_1, hash_2, hash_3]

In [625]:
print(hash_list)

[<function <lambda> at 0x114440860>, <function <lambda> at 0x114441120>, <function <lambda> at 0x114440e00>]


In [626]:
## Using the hash functions and the input matrix compute the MinHash signature matrix here ##

# for the rows in the input matrix check if there are 1s in any column, and then apply the hash function to that (row, col) 
# and update the signature matrix if the hash value is smaller than the existing value in the signature matrix
for r in range(np.shape(input_matrix)[0]):
    for c in range( len(sentences)):
        if input_matrix[r][c] == 1:
            for i in range(len(hash_list)):
                # since the sentences are 0-indexed, we add 1 to get the correct hash value
                if hash_list[i](r+1) < Sig_M[i][c]:
                    Sig_M[i][c] = hash_list[i](r+1)
                
        

In [627]:
# print the updated MinHash signature matrix

Sig_M

array([[1., 2., 1., 2.],
       [1., 2., 1., 2.],
       [2., 1., 2., 3.]])